### ISSUE TITLE
Nightwatchjs try start test and get this error import type {Callback, ListenedXHR} from "../types" - SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by SergeyRekhin** [cortexmg/nightwatch-xhr#17]
Hello.
Thank u for this module, but i have an error when trying to start a test that wrote on Nighwatchjs testframework. Then i installed - npm i babel-plugin-add-module-exports babel-core babel-preset-es2015 --save-dev and added require ('babel-register')() to nighwatch.json.js file, but this was not helps.
Can you help me?

> import type {Callback, ListenedXHR} from "../types";
^^^^^^
SyntaxError: Unexpected token import
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Module._extensions..js (module.js:579:10)

**Comment by SergeyRekhin** [comment]
my falls. sorry

**Comment by carloseduleal** [comment]
I'm getting this issue right now, there is any update about this? @SergeyRekhin how did you solve it?
