### ISSUE TITLE
XHR Callback functions - we are not getting the response code, data

### ISSUE THREAD

**Issue by nvellanki** [cortexmg/nightwatch-xhr#19]
We are able to get request data, but no response data.

Code:
browser.listenXHR()
            .click('xxxxxxxx')
            .getXHR('xxx-xxx', 10000, function (xhr) {
                console.log(xhr);
            });

XHR Callback output: 
[ { openedTime: 1518047426587,
    id: 'XXXXXXXX',
    method: 'POST',
    requestData: 'XXXXXXXXXX',
    url: 'https://www.xxxx.com/xxxx' } ]

Is there any open issue related to response data?

**Comment by JalilArfaoui** [comment]
Hello @nvellanki 

Good question. I must say I don't use `responseData` myself, let me check what's going on.

**Comment by vishvasNagpal** [comment]
is there any update on this.

**Comment by orta-sanz** [comment]
Same here, any update? thanks guys :)

**Comment by Botz** [comment]
I am getting the same error for api requests with JSON response.
An i am getting the following in the browser console:
DOMException: Failed to read the 'responseText' property from 'XMLHttpRequest'

I think you should use this.response to get the responseData

If i find some time i will make a PR for this

**Comment by DustinOgan** [comment]
https://github.com/cortexmg/nightwatch-xhr/commit/db78801368c219c6bbfa32385cd7dfc6fb203884#diff-cf27c1d543e886c89cd9ac8b8aeaf05b

this is where this was removed i think .  Someone gutted the responseData stuff as a fix for a crash type

**Comment by DustinOgan** [comment]
client.js line 35 should be 
this.onloadend = function () {

This correction will allow the response data to be populated. I can submit a PR

**Comment by segrey11** [comment]
Thanks, have the same issue. Your advice helped

> client.js line 35 should be
> this.onloadend = function () {
> 
> This correction will allow the response data to be populated. I can submit a PR if you'd like or you can update the code.

**Comment by Eriusik** [comment]
Thanks! it works for me too



> client.js line 35 should be
> this.onloadend = function () {
> 
> This correction will allow the response data to be populated. I can submit a PR if you'd like or you can update the code.
