### ISSUE TITLE
Listen XHR doesn't return all XHRs

### ISSUE THREAD

**Issue by Pieras2** [cortexmg/nightwatch-xhr#42]
This returns empty array < why ??

```js module.exports = {
    'LogIn': function (browser) {
        browser
            .url(browser.globals.baseUrl, function () {
                browser
                    .pause(1000)
                    .assert.urlContains(browser.globals.loginUrl)
            })
            .waitForElementVisible('#email-input')
            .setValue(selector.LOGIN.EMAIL, browser.globals.user_credentials.login)
            .setValue(selector.LOGIN.PASSWORD, atob(browser.globals.user_credentials.password))

            // .listenXHR()
            .waitForXHR('.*', 5000, function () {
                browser
                    .click(selector.LOGIN.SIGNIN)
                    .waitForElementVisible(selector.BUTTONS.UPLOAD)
            }, (xhrs) => {
                console.log(xhrs);
            })
```

This returns XHR from specific path and it works

```js
module.exports = {
    'LogIn': function (browser) {
        browser
            .url(browser.globals.baseUrl, function () {
                browser
                    .pause(1000)
                    .assert.urlContains(browser.globals.loginUrl)
            })
            .waitForElementVisible('#email-input')
            .setValue(selector.LOGIN.EMAIL, browser.globals.user_credentials.login)
            .setValue(selector.LOGIN.PASSWORD, atob(browser.globals.user_credentials.password))
            .click(selector.LOGIN.SIGNIN)
            .listenXHR()
            .waitForElementVisible(selector.BUTTONS.UPLOAD)
            .getXHR('connect/userinfo', 1000, function (xhrs) {
                // organization_id = (JSON.parse(xhrs[0].responseData).organization_id);
                // organization_user_id = (JSON.parse(xhrs[0].responseData).organization_user_id);
                // sub = (JSON.parse(xhrs[0].responseData).sub);
                console.log(xhrs)
            })
    }
}
```

This returns some array of XHRs but only some of them < why ?

```js
module.exports = {
    'LogIn': function (browser) {
        browser
            .url(browser.globals.baseUrl, function () {
                browser
                    .pause(1000)
                    .assert.urlContains(browser.globals.loginUrl)
            })
            .waitForElementVisible('#email-input')
            .setValue(selector.LOGIN.EMAIL, browser.globals.user_credentials.login)
            .setValue(selector.LOGIN.PASSWORD, atob(browser.globals.user_credentials.password))
            .click(selector.LOGIN.SIGNIN)
            .listenXHR()
            .waitForElementVisible(selector.BUTTONS.UPLOAD)
            .getXHR('', 1000, function (xhrs) {
                // organization_id = (JSON.parse(xhrs[0].responseData).organization_id);
                // organization_user_id = (JSON.parse(xhrs[0].responseData).organization_user_id);
                // sub = (JSON.parse(xhrs[0].responseData).sub);
                console.log(xhrs)
            })
    }
}

```

Is it an issue or I do something wrong??

**Comment by Pieras2** [comment]
I solved it on my own - I'm not a programmer, just reading and trying ;-)

In file **client.js**, prior line **this.onloadend = function () ** just make a copy of this method and copy above with **this.onload = function ()**

Now I get all XHRs I wished to get.

**Comment by Amitm11** [comment]
@Pieras2 Could you please help me resolving the same issue? I had made changes in the client.js file as mentioned by you, but no luck. Below is the login method.

    'Login via Antuit Azure AD' : function(browser, loginPage, username, pwd) {
        browser
            if(loginPage.assert.elementPresent('@azureAD')) {
                console.log('Antuit Azure AD link is presnt on the Login page')
                loginPage.click('@azureAD')
                loginPage.waitForElementVisible('@nextBtn', 7000)
                loginPage.setValue('@antuitEmail', username)
              
                loginPage.click('@nextBtn')
                loginPage.waitForElementVisible('@signinBtn', 7000)
                loginPage.setValue('@antuitPassword', pwd)
                loginPage.click('@signinBtn')
               
                loginPage.waitForElementVisible('@noBtn', 7000)           
                loginPage.click('@noBtn')
                browser.pause(15000)
                
                browser.listenXHR()
                browser.getXHR('', 1000, function (xhrs) {
                     **console.log('xhrs: '+xhrs)**
                })
}

Following is the console log after execution
√ Login page opened (13ms)
Running:  Login to application

Antuit Azure AD link is presnt on the Login page
√ Testing if element <Element [name=@azureAD]> is present (21ms)
√ Element <input[id="idSIButton9"]> was visible after 574 milliseconds.
√ Element <input[value="Sign in"]> was visible after 2605 milliseconds.
√ Element <input[value="No"]> was visible after 556 milliseconds.
**xhrs:** 
√ Passed [equal]: Login Successfull !!!

OK. 5 assertions passed. (37.987s)
Running:  Verify All tabs open properly

**Comment by Pieras2** [comment]
Hi, I abandoned this npm package.
If you made the code the way I was mentioning it means only that the nw-xhr
doesn't work with your page. On my request my 2 collegues found solution
for sniffing traffic. They used browser mob proxy and some ajax code that
does the thing. You would start proxy, do all you need and then similarly
to nw-hxr just read the buffer with collected data. I will talk to them to
ask them to describe the solution.

czw., 8 paź 2020, 18:59 użytkownik Amitm11 <notifications@github.com>
napisał:
