### ISSUE TITLE
[Bug] Failed to load getXHR.js

### ISSUE THREAD

**Issue by Bugazelle** [cortexmg/nightwatch-xhr#50]
Hello ALL,

Anyone could give me a quick help about the issue?
I am not sure where is wrong
Maybe it is a bug?

<img width="800" alt="Screen Shot 2020-05-28 at 4 03 00 PM" src="https://user-images.githubusercontent.com/44971345/83115525-0e946e00-a0fd-11ea-9057-0eac331d18b0.png">

**Comment by ttlpta** [comment]
Hi @Bugazelle , How did you solve this issue?
